categories:
  cooking:
    routes:
      en: cooking
      nl: koken
    public: true
  horses:
    routes:
      en: horse-riding
      nl: paardrijden
    public: true
  entertainment:
    routes:
      en: entertainment
      nl: vrije-tijd
    public: true

applications:
  horse-riding-log:
    category: horses
    routes:
      en: rides
      nl: log
    public: false
    order: 3
    deactivate: false

  horse-riding-events:
    category: horses
    routes:
      en: events
      nl: wedstrijden
    public: true
    order: 4

  horses-riders:
    category: horses
    routes:
      en: riders
      nl: ruiters
    public: false
    order: 5

  horse-riding-instructors:
    category: horses
    routes:
      en: instructors
      nl: instructeurs
    public: false
    order: 5


  horses-stables:
    category: horses
    routes:
      en: stables
      nl: maneges
    public: false
    order: 10

  horses-main:
    category: horses
    routes:
      en: horses
      nl: paarden
    public: true
    order: 0

  horses-gear:
    category: horses
    routes:
      en: gear
      nl: uitrusting
    public: false
    order: 99

  cooking:
    category: cooking
    routes:
      en: recipes
      nl: recepten
    public: true
    order: -1

  ent-reviews:
    category: entertainment
    routes:
      en: bad-reviews
      nl: reviews
    public: true
    order: 0

  #tasks:
  #  routes:
  #   en: tasker
  #   nl: tasker
  #  public: false
