application:
    name: riding instructors

    fields:
        photo:
            type: image
        stables:
            type: choice
            label: Riding school
            source: stables
            required: true
        name:
            type: text
            maxlength: 150
            required: true
            unique: true
        lessons:
            source: rides
            type: number
            required: true
        average:
            label: average score
            source: avg_score
            type: number
            dashboard: large
            _transform:
                number:
                    round: true
                    round_precision: 1

    modules:
      detail:
        enabled: false


    meta:
        exposes: name
        sort: [stables, name]

    sources:
        stables:
            application: horses-stables
        rides:
            application: horse-riding-log
            function: count
            link: dashboard
        avg_score:
            application: horse-riding-log
            function: avg
            field: rating_instructions
            invert_join: true

